name: image_captioning
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - spacy
  - pillow
  - pytorch
  - torchvision
  - torchtext
  - cudatoolkit=11.8  #Compatibility
  - pip
  - pip:
      - nltk

    # Commands to run after environment setup
    #pip install torchtext, if needed
    #python -m spacy download en_core_web_lg

