name: image_captioning
channels:
  - nvidia
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.24
  - pandas
  - matplotlib
  - spacy
  - pillow
  - pytorch=2.1.1
  - torchvision=0.16.1
  - torchaudio=2.1.1
  - pytorch-cuda=11.8
  - torchtext=0.16.1
  - pip
  - pip:
      - nltk

    # Commands to run after environment setup
    #pip install torchtext, if needed
    #python -m spacy download en_core_web_lg
    #pip install spacy==3.8.0 for compatibility with en_core_web_lg
    #pip install git+https://github.com/salaniz/pycocoevalcap
    #Jave for Meteor score: https://www.java.com/en/download/



